from data_process import *

# 5G SSV KPI
SSV_NR_DL_THROUGHPUT_KPI = 'RLC Throughput NR-DL RLC DL RLC Throughput [Mbps]'
SSV_ENDC_DL_THROUGHPUT_KPI = 'Total Info Layer2 PDCP DL Throughput(+Split Bearer) [Mbps]'
SSV_NR_UL_THROUGHPUT_KPI = 'RLC Throughput NR-UL RLC UL RLC Throughput [Mbps]'
SSV_ENDC_UL_THROUGHPUT_KPI = 'Total Info Layer2 PDCP UL Throughput(+Split Bearer) [Mbps]'
# LTE SSV KPI
SSV_LTE_DL_THROUGHPUT_KPI = 'LTE KPI RLC DL Throughput [Mbps]'
SSV_CA_DL_THROUGHPUT_KPI = 'LTE KPI PDCP DL Throughput [Mbps]'
SSV_LTE_UL_THROUGHPUT_KPI = 'LTE KPI RLC UL Throughput [Mbps]'
SSV_CA_UL_THROUGHPUT_KPI = 'LTE KPI RLC UL Throughput [Mbps]'
XCAL_TIME_STAMP = 'TIME_STAMP'

nr_ssv_dl_thp_export_list = [[DT_LOG_LON],
                             [DT_LOG_LAT],
                             ['5G-NR RLC Throughput NR-DL RLC DL RLC Throughput [Mbps]'],
                             ['5G-NR PCell RF Serving PCI'], ['5G-NR PCell RF NR-ARFCN'],
                             ['5G-NR PCell RF Serving SS-RSRP [dBm]'], ['5G-NR PCell RF Serving SS-SINR [dB]'],
                             ['5G-NR PCell Layer1 DL BLER [%]'], ['5G-NR PCell Layer1 DL Layer Num (Avg)'],
                             ['5G-NR PCell Layer1 DL MCS (Avg)'],
                             ['Qualcomm 5G-NR MAC PDSCH Info PCell RB Num[Avg]',
                              'Qualcomm 5G-NR MAC PDSCH Info PCell RB Num[Including 0]']]

nr_ssv_ul_thp_export_list = [[DT_LOG_LON],
                             [DT_LOG_LAT],
                             ['5G-NR RLC Throughput NR-UL RLC UL RLC Throughput [Mbps]'],
                             ['5G-NR PCell RF Serving PCI'], ['5G-NR PCell RF NR-ARFCN'], ['5G-NR PCell RF Serving SS-RSRP [dBm]'],
                             ['5G-NR PCell RF Serving SS-SINR [dB]'], ['5G-NR PCell Layer1 UL BLER [%]'],
                             ['5G-NR PCell Layer1 UL MCS (Avg)'],
                             ['5G-NR PCell Layer1 UL RB Num (Including 0)', '5G-NR PCell Layer1 UL RB Num (Avg)'],
                             ['Qualcomm 5G-NR MAC PUSCH Info PCell Layer Num[Avg]']]

endc_ssv_dl_thp_export_list = [[DT_LOG_LON],
                               [DT_LOG_LAT],
                               ['5G KPI Total Info Layer2 PDCP DL Throughput(+Split Bearer) [Mbps]',
                                '5G KPI Total Info Layer2 RLC DL Throughput [Mbps]',
                                'LTE KPI RLC DL Throughput [Mbps]', 'LTE KPI MAC DL Throughput [Mbps]'],
                               ['5G-NR PCell RF Serving PCI', 'LTE KPI PCell Serving PCI'],
                               # ['5G-NR PCell RF NR-ARFCN'], ['LTE KPI PCell Serving EARFCN(DL)'],
                               ['5G-NR PCell RF Serving SS-RSRP [dBm]', 'LTE KPI PCell Serving RSRP [dBm]'],
                               ['5G-NR PCell RF Serving SS-SINR [dB]', 'LTE KPI PCell SINR [dB]'],
                               ['5G-NR PCell RF RI', 'LTE KPI PCell WB RI'],
                               ['5G-NR PCell Layer1 DL MCS (Avg)', 'LTE KPI PCell DL MCS0', 'LTE KPI PCell DL MCS1'],
                               ['5G-NR PCell Layer1 DL RB Num (Avg)',
                                '5G-NR PCell Layer1 DL RB Num (Including 0)',
                                'LTE KPI PCell PDSCH PRB Number(Avg)'],
                               ['5G-NR PCell Layer1 DL BLER [%]', 'LTE KPI PCell PDSCH BLER [%]']]

endc_thick_ssv_dl_thp_export_list = [[DT_LOG_LON],
                               [DT_LOG_LAT],
                               ['Total Info Layer2 PDCP DL Throughput(+Split Bearer) [Mbps]',
                                'Total Info Layer2 RLC DL Throughput [Mbps]',
                                'LTE KPI RLC DL Throughput [Mbps]',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 MAC DL Throughput',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 MAC DL Throughput',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 MAC DL Throughput',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 MAC DL Throughput'],
                               ['5G-NR PCell RF Serving PCI', 'LTE KPI PCell Serving PCI',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 Serving PCI',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 Serving PCI',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 Serving PCI',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 Serving PCI'],
                               ['LTE KPI PCell Serving EARFCN(DL)'],
                               ['5G-NR PCell RF Serving SS-RSRP [dBm]', 'LTE KPI PCell Serving RSRP [dBm]',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 Serving RSRP',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 Serving RSRP',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 Serving RSRP',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 Serving RSRP'],
                               ['5G-NR PCell RF Serving SS-SINR [dB]', 'LTE KPI PCell SINR [dB]',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 SINR',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 SINR',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 SINR',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 SINR'],
                               ['5G-NR PCell RF RI', 'LTE KPI PCell WB RI',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 WB RI',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 WB RI',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 WB RI',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 WB RI'],
                               ['5G-NR PCell Layer1 DL MCS (Avg)', 'LTE KPI PCell DL MCS0',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 DL MCS0',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 DL MCS0',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 DL MCS0',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 DL MCS0'],
                               ['5G-NR PCell Layer1 DL MCS (Avg)', 'LTE KPI PCell DL MCS1',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 DL MCS1',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 DL MCS1',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 DL MCS1',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 DL MCS1'],
                               ['5G-NR PCell Layer1 DL RB Num (Avg)',
                                '5G-NR PCell Layer1 DL RB Num (Including 0)',
                                'LTE KPI PCell PDSCH PRB Number(Avg)',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 PDSCH PRB Number',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 PDSCH PRB Number',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 PDSCH PRB Number',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 PDSCH PRB Number'],
                               ['5G-NR PCell Layer1 DL BLER [%]', 'LTE KPI PCell PDSCH BLER [%]',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 PDSCH BLER',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 PDSCH BLER',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 PDSCH BLER',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 PDSCH BLER'],
                               ['5G-NR PCell RF CQI', 'LTE KPI PCell WB CQI CW0',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 WB CQI CW0',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 WB CQI CW0',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 WB CQI CW0',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 WB CQI CW0'],
                               ['5G-NR PCell RF CQI', 'LTE KPI PCell WB CQI CW1',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 WB CQI CW1',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 WB CQI CW1',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 WB CQI CW1',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 WB CQI CW1'],
                               ['LTE KPI CA Type'],
                               ['LTE KPI Band Combination']]

lte_thick_ssv_dl_thp_export_list = [[DT_LOG_LON],
                               [DT_LOG_LAT],
                               ['LTE KPI RLC DL Throughput [Mbps]',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 MAC DL Throughput',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 MAC DL Throughput',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 MAC DL Throughput',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 MAC DL Throughput'],
                               ['LTE KPI PCell Serving PCI',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 Serving PCI',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 Serving PCI',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 Serving PCI',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 Serving PCI'],
                               ['LTE KPI PCell Serving EARFCN(DL)'],
                               ['LTE KPI PCell Serving RSRP [dBm]',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 Serving RSRP',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 Serving RSRP',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 Serving RSRP',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 Serving RSRP'],
                               ['LTE KPI PCell SINR [dB]',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 SINR',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 SINR',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 SINR',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 SINR'],
                               ['LTE KPI PCell WB RI',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 WB RI',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 WB RI',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 WB RI',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 WB RI'],
                               ['LTE KPI PCell DL MCS0',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 DL MCS0',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 DL MCS0',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 DL MCS0',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 DL MCS0'],
                               ['LTE KPI PCell DL MCS1',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 DL MCS1',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 DL MCS1',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 DL MCS1',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 DL MCS1'],
                               ['LTE KPI PCell PDSCH PRB Number(Avg)',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 PDSCH PRB Number',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 PDSCH PRB Number',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 PDSCH PRB Number',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 PDSCH PRB Number'],
                               ['LTE KPI PCell PDSCH BLER [%]',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 PDSCH BLER',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 PDSCH BLER',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 PDSCH BLER',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 PDSCH BLER'],
                               ['LTE KPI PCell WB CQI CW0',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 WB CQI CW0',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 WB CQI CW0',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 WB CQI CW0',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 WB CQI CW0'],
                               ['LTE KPI PCell WB CQI CW1',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 WB CQI CW1',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 WB CQI CW1',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 WB CQI CW1',
                                'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 WB CQI CW1'],
                               ['LTE KPI CA Type'],
                               ['LTE KPI Band Combination']]

endc_ssv_ul_thp_export_list = [[DT_LOG_LON],
                               [DT_LOG_LAT],
                               ['Total Info Layer2 PDCP UL Throughput(+Split Bearer) [Mbps]',
                                'Total Info Layer2 RLC UL Throughput [Mbps]',
                                'LTE KPI RLC UL Throughput [Mbps]'],
                               ['5G-NR PCell RF Serving PCI', 'LTE KPI PCell Serving PCI'],
                               # ['5G-NR PCell RF NR-ARFCN'], ['LTE KPI PCell Serving EARFCN(DL)'],
                               ['5G-NR PCell RF Serving SS-RSRP [dBm]', 'LTE KPI PCell Serving RSRP [dBm]'],
                               ['5G-NR PCell RF Serving SS-SINR [dB]', 'LTE KPI PCell SINR [dB]'],
                               ['5G-NR PCell Layer1 UL MCS (Avg)', 'LTE KPI PCell UL MCS'],
                               ['5G-NR PCell Layer1 UL RB Num (Avg)', '5G-NR PCell Layer1 UL RB Num (Including 0)',
                                'LTE KPI PCell PUSCH PRB Number(Avg)'],
                               ['5G-NR PCell Layer1 UL BLER [%]', 'LTE KPI PCell PUSCH BLER [%]'],
                               ['LTE KPI PCell Total Tx Power [dBm]', 'LTE KPI PCell PUSCH Power [dBm]']]


lte_ssv_dl_thp_export_list = [[DT_LOG_LON],
                              [DT_LOG_LAT],
                               ['LTE KPI RLC DL Throughput [Mbps]', 'LTE KPI MAC DL Throughput [Mbps]'], #'APP All FWD Throughput (kbps)'],
                               ['LTE KPI PCell Serving PCI'],
                               ['LTE KPI PCell Serving EARFCN(DL)'],
                               ['LTE KPI PCell Serving RSRP [dBm]'],
                               ['LTE KPI PCell SINR [dB]'],
                               ['LTE KPI PCell WB RI'],
                               ['LTE KPI PCell DL MCS0', 'LTE KPI PCell DL MCS1'],
                               ['LTE KPI PCell PDSCH PRB Number(Avg)', 'LTE KPI PCell PDSCH PRB Number(Including 0)'],
                               ['LTE KPI PCell PDSCH BLER [%]'],
                               ['LTE KPI PCell PUSCH BLER [%]'],
                               ['LTE KPI PCell WB CQI CW0', 'LTE KPI PCell WB CQI CW1']]

lte_ssv_ul_thp_export_list = [[DT_LOG_LON],
                               [DT_LOG_LAT],
                               ['LTE KPI RLC UL Throughput [Mbps]'], #'APP All RVS Throughput (kbps)'],
                               ['LTE KPI PCell Serving PCI'],
                               ['LTE KPI PCell Serving EARFCN(DL)'],
                               ['LTE KPI PCell Serving RSRP [dBm]'],
                               ['LTE KPI PCell SINR [dB]'],
                               ['LTE KPI PCell UL MCS'],
                               ['LTE KPI PCell PUSCH PRB Number(Avg)', 'LTE KPI PCell PUSCH PRB Number(Including 0)'],
                               ['LTE KPI PCell PDSCH BLER [%]'],
                               ['LTE KPI PCell PUSCH BLER [%]'],
                               ['LTE KPI PCell Total Tx Power [dBm]', 'LTE KPI PCell PUSCH Power [dBm]']]
                               #['LL1 Uplink Info PCell Path Loss [dB]']]

lte_ssv_ca_dl_thp_export_list = [[DT_LOG_LON],
                               [DT_LOG_LAT],
                               [#'APP All FWD Throughput (kbps)',
                                'LTE KPI RLC DL Throughput [Mbps]',
                                'LTE KPI PCell MAC DL Throughput [Mbps]',
                                'LTE KPI SCell[1] SCell[1] MAC DL Throughput [Mbps]',
                                'LTE KPI SCell[2] SCell[2] MAC DL Throughput [Mbps]',
                                'LTE KPI SCell[3] SCell[3] MAC DL Throughput [Mbps]',
                                'LTE KPI SCell[4] SCell[4] MAC DL Throughput [Mbps]'],
                               ['LTE KPI PCell Serving PCI', 'LTE KPI SCell[1] SCell[1] Serving PCI',
                                'LTE KPI SCell[2] SCell[2] Serving PCI', 'LTE KPI SCell[3] SCell[3] Serving PCI',
                                'LTE KPI SCell[4] SCell[4] Serving PCI'],
                               ['LTE KPI PCell Serving EARFCN(DL)',
                                'LTE KPI SCell[1] SCell[1] Serving EARFCN(DL)',
                                'LTE KPI SCell[2] SCell[2] Serving EARFCN(DL)', 'LTE KPI SCell[3] SCell[3] Serving EARFCN(DL)',
                                'LTE KPI SCell[4] SCell[4] Serving EARFCN(DL)'],
                               ['LTE KPI PCell Serving RSRP [dBm]', 'LTE KPI SCell[1] SCell[1] Serving RSRP [dBm]',
                                'LTE KPI SCell[2] SCell[2] Serving RSRP [dBm]', 'LTE KPI SCell[3] SCell[3] Serving RSRP [dBm]',
                                'LTE KPI SCell[4] SCell[4] Serving RSRP [dBm]'],
                               ['LTE KPI PCell SINR [dB]', 'LTE KPI PCell SINR [dB]', 'LTE KPI SCell[1] SCell[1] SINR [dB]',
                                'LTE KPI SCell[2] SCell[2] SINR [dB]', 'LTE KPI SCell[3] SCell[3] SINR [dB]',
                                'LTE KPI SCell[4] SCell[4] SINR [dB]'],
                               ['LTE KPI PCell WB RI', 'LTE KPI PCell WB RI', 'LTE KPI SCell[1] SCell[1] WB RI',
                                'LTE KPI SCell[2] SCell[2] WB RI', 'LTE KPI SCell[3] SCell[3] WB RI',
                                'LTE KPI SCell[4] SCell[4] WB RI'],
                               ['LTE KPI PCell DL MCS0', 'LTE KPI SCell[1] SCell[1] DL MCS0', 'LTE KPI SCell[2] SCell[2] DL MCS0',
                                'LTE KPI SCell[3] SCell[3] DL MCS0', 'LTE KPI SCell[4] SCell[4] DL MCS0'],
                               ['LTE KPI PCell DL MCS1', 'LTE KPI SCell[1] SCell[1] DL MCS1', 'LTE KPI SCell[2] SCell[2] DL MCS1',
                                'LTE KPI SCell[3] SCell[3] DL MCS1', 'LTE KPI SCell[4] SCell[4] DL MCS1'],
                               ['LTE KPI PCell PDSCH PRB Number(Avg)', 'LTE KPI SCell[1] SCell[1] PDSCH PRB Number(Avg)',
                                'LTE KPI SCell[2] SCell[2] PDSCH PRB Number(Avg)', 'LTE KPI SCell[3] SCell[3] PDSCH PRB Number(Avg)',
                                'LTE KPI SCell[4] SCell[4] PDSCH PRB Number(Avg)'],
                               ['LTE KPI PCell PDSCH PRB Number(Including 0)', 'LTE KPI SCell[1] SCell[1] PDSCH PRB Number(Including 0)',
                                'LTE KPI SCell[2] SCell[2] PDSCH PRB Number(Including 0)', 'LTE KPI SCell[3] SCell[3] PDSCH PRB Number(Including 0)',
                                'LTE KPI SCell[4] SCell[4] PDSCH PRB Number(Including 0)'],
                               ['LTE KPI PCell PDSCH BLER [%]', 'LTE KPI SCell[1] SCell[1] PDSCH BLER [%]',
                                'LTE KPI SCell[2] SCell[2] PDSCH BLER [%]', 'LTE KPI SCell[3] SCell[3] PDSCH BLER [%]',
                                'LTE KPI SCell[4] SCell[4] PDSCH BLER [%]'],
                               ['LTE KPI PCell WB CQI CW0', 'LTE KPI PCell WB CQI CW1'],
                               ['LTE KPI SCell[1] SCell[1] WB CQI CW0', 'LTE KPI SCell[1] SCell[1] WB CQI CW1'],
                               ['LTE KPI SCell[2] SCell[2] WB CQI CW0', 'LTE KPI SCell[2] SCell[2] WB CQI CW1'],
                               ['LTE KPI SCell[3] SCell[3] WB CQI CW0', 'LTE KPI SCell[3] SCell[3] WB CQI CW1'],
                               ['LTE KPI SCell[4] SCell[4] WB CQI CW0', 'LTE KPI SCell[4] SCell[4] WB CQI CW1']]

lte_ssv_ca_ul_thp_export_list = [[DT_LOG_LON],
                               [DT_LOG_LAT],
                               [#'APP All RVS Throughput (kbps)',
                                'LTE KPI RLC UL Throughput [Mbps]',
                                'LTE KPI PCell MAC UL Throughput [Mbps]',
                                'LTE KPI SCell[1] SCell[1] MAC UL Throughput [Mbps]'],
                               ['LTE KPI PCell Serving EARFCN(DL)',
                                'LTE KPI SCell[1] SCell[1] Serving EARFCN(DL)'],
                               ['LTE KPI PCell Serving PCI', 'LTE KPI SCell[1] SCell[1] Serving PCI'],
                               ['LTE KPI PCell Serving RSRP [dBm]', 'LTE KPI SCell[1] SCell[1] Serving RSRP [dBm]'],
                               ['LTE KPI PCell SINR [dB]', 'LTE KPI SCell[1] SCell[1] SINR [dB]'],
                               ['LTE KPI PCell UL MCS', 'LTE KPI SCell[1] SCell[1] UL MCS'],
                               ['LTE KPI PCell PUSCH PRB Number(Avg)', 'LTE KPI PCell PUSCH PRB Number(Including 0)', 'LTE KPI SCell[1] SCell[1] PUSCH PRB Number(Avg)'],
                               ['LTE KPI PCell PUSCH BLER [%]', 'LTE KPI SCell[1] SCell[1] PUSCH BLER [%]'],
                               ['LTE KPI PCell Total Tx Power [dBm]', 'LTE KPI SCell[1] SCell[1] Total Tx Power [dBm]'],
                               ['LTE KPI PCell PUSCH Power [dBm]', 'LTE KPI SCell[1] SCell[1] PUSCH Power [dBm]']]

endc_DT_dl_thp_export_list = [[DT_LOG_LON],
                               [DT_LOG_LAT],
                               ['5G-NR EN-DC RLC Throughput DL RLC Throughput(Total PDU) Total DL RLC Throughput [Mbps]',
                                '5G-NR RLC Throughput NR-DL RLC DL RLC Throughput [Mbps]',
                                'LTE KPI RLC DL Throughput [Mbps]', 'LTE KPI PCell MAC DL Throughput [Mbps]'],
                               ['5G-NR PCell RF Serving PCI', 'LTE KPI PCell Serving PCI'],
                               ['5G-NR PCell RF NR-ARFCN'], ['LTE KPI PCell Serving EARFCN(DL)'],
                               ['5G-NR PCell RF Serving SS-RSRP [dBm]', 'LTE KPI PCell Serving RSRP [dBm]'],
                               ['5G-NR PCell RF Serving SS-SINR [dB]', 'LTE KPI PCell SINR [dB]'],
                               ['5G-NR PCell Layer1 DL Layer Num (Avg)', 'LTE KPI PCell WB RI'],
                               ['5G-NR PCell Layer1 DL MCS (Avg)', 'LTE KPI PCell DL MCS0', 'LTE KPI PCell DL MCS1'],
                               ['5G-NR PCell Layer1 DL RB Num (Avg)',
                                '5G-NR MAC PDSCH Info PCell RB Num[Including 0]',
                                'LTE KPI PDSCH PRB Number(Avg)(Total)'],
                               ['5G-NR PCell Layer1 DL BLER [%]', 'LTE KPI PCell PDSCH BLER [%]']]

Spark_DT_ENDC_DL_Export_list = [[DT_LOG_LON], [DT_LOG_LAT],
                                ['5G KPI Total Info Layer2 PDCP DL Throughput(+Split Bearer) [Mbps]',
                                '5G KPI Total Info Layer2 RLC DL Throughput [Mbps]',
                                '5G KPI Total Info Layer2 MAC DL Throughput [Mbps]',
                                'LTE KPI MAC DL Throughput [Mbps]'],
                                ['5G-NR PCell RF Serving PCI', 'LTE KPI PCell Serving PCI'],
                                ['5G-NR PCell RF Serving SS-RSRP [dBm]', 'LTE KPI PCell Serving RSRP [dBm]'],
                                ['5G-NR PCell RF Serving SS-SINR [dB]', 'LTE KPI PCell SINR [dB]'],
                                ['5G-NR PCell RF Serving SS-RSRQ [dB]', 'LTE KPI PCell Serving RSRQ [dB]'],
                                ['5G-NR PCell RF RI', 'LTE KPI PCell WB RI'],
                                ['5G-NR PCell Layer1 DL MCS (Avg)', 'LTE KPI PCell DL MCS0', 'LTE KPI PCell DL MCS1'],
                                ['5G-NR PCell Layer1 DL RB Num (Avg)',
                                '5G-NR PCell Layer1 DL RB Num (Including 0)',
                                'LTE KPI PCell PDSCH PRB Number(Avg)'],
                                ['5G-NR PCell Layer1 DL BLER [%]', 'LTE KPI PCell PDSCH BLER [%]'],
                              ['5G-NR PCell RF CQI', 'LTE KPI PCell WB CQI CW0', 'LTE KPI PCell WB CQI CW1']]

Spark_DT_ENDC_UL_Export_list = [[DT_LOG_LON], [DT_LOG_LAT],
                                ['5G-NR Total Info Layer2 PDCP UL Throughput(+Split Bearer) [Mbps]',
                                '5G-NR Total Info Layer2 RLC DL Throughput [Mbps]',
                                '5G-NR Total Info Layer2 MAC DL Throughput [Mbps]',
                                'LTE KPI MAC UL Throughput [Mbps]'],
                                ['5G-NR PCell RF Serving PCI', 'LTE KPI PCell Serving PCI'],
                                ['5G-NR PCell RF Serving SS-RSRP [dBm]', 'LTE KPI PCell Serving RSRP [dBm]'],
                                ['5G-NR PCell RF Serving SS-SINR [dB]', 'LTE KPI PCell SINR [dB]'],
                                ['5G-NR PCell RF Serving SS-RSRQ [dB]', 'LTE KPI PCell Serving RSRQ [dB]'],
                                ['5G-NR PCell RF PUSCH Power [dBm]', 'LTE KPI PCell PUSCH Power [dBm]',
                                 'LTE KPI PCell Total Tx Power [dBm]'],
                                ['5G-NR PCell Layer1 UL MCS (Avg)', 'LTE KPI PCell UL MCS'],
                                ['5G-NR PCell Layer1 DL RB Num (Avg)',
                                '5G-NR PCell Layer1 DL RB Num (Including 0)',
                                'LTE KPI PCell PUSCH PRB Number(Avg)'],
                                ['5G-NR PCell Layer1 DL BLER [%]', 'LTE KPI PCell PUSCH BLER [%]']]

Spark_DT_NR_DL_Export_list = [[DT_LOG_LON],
                               [DT_LOG_LAT],
                               ['5G KPI Total Info Layer2 PDCP DL Throughput(+Split Bearer) [Mbps]',
                                '5G KPI Total Info Layer2 RLC DL Throughput [Mbps]', 'LTE KPI MAC DL Throughput [Mbps]'],
                               ['5G-NR PCell RF Serving PCI', 'LTE KPI PCell Serving PCI'],
                               ['5G-NR PCell RF Serving SS-RSRP [dBm]', 'LTE KPI PCell Serving RSRP [dBm]'],
                               ['5G-NR PCell RF Serving SS-SINR [dB]', 'LTE KPI PCell SINR [dB]'],
                               ['5G-NR PCell RF Serving SS-RSRQ [dB]', 'LTE KPI PCell Serving RSRQ [dB]'],
                               ['5G-NR PCell RF RI', 'LTE KPI PCell WB RI'],
                               ['5G-NR PCell Layer1 DL MCS (Avg)', 'LTE KPI PCell DL MCS0', 'LTE KPI PCell DL MCS1'],
                               ['5G-NR PCell Layer1 DL RB Num (Avg)',
                                '5G-NR PCell Layer1 DL RB Num (Including 0)',
                                'LTE KPI PCell PDSCH PRB Number(Avg)'],
                               ['5G-NR PCell Layer1 DL BLER [%]', 'LTE KPI PCell PDSCH BLER [%]'],
                              ['5G-NR PCell RF CQI', 'LTE KPI PCell WB CQI CW0', 'LTE KPI PCell WB CQI CW1']]

Spark_DT_NR_DL_Export_list2 = [[DT_LOG_LON],
                               [DT_LOG_LAT],
                               ['5G-NR Total Info Layer2 PDCP DL Throughput(+Split Bearer) [Mbps]',
                                '5G-NR Total Info Layer2 RLC DL Throughput [Mbps]', 'LTE KPI MAC DL Throughput [Mbps]'],
                               ['5G-NR PCell RF Serving PCI', 'LTE KPI PCell Serving PCI'],
                               ['5G-NR PCell RF Serving SS-RSRP [dBm]', 'LTE KPI PCell Serving RSRP [dBm]'],
                               ['5G-NR PCell RF Serving SS-SINR [dB]', 'LTE KPI PCell SINR [dB]'],
                               ['5G-NR PCell RF Serving SS-RSRQ [dB]', 'LTE KPI PCell Serving RSRQ [dB]'],
                               ['5G-NR PCell RF RI', 'LTE KPI PCell WB RI'],
                               ['5G-NR PCell Layer1 DL MCS (Avg)', 'LTE KPI PCell DL MCS0', 'LTE KPI PCell DL MCS1'],
                               ['5G-NR PCell Layer1 DL RB Num (Avg)',
                                '5G-NR PCell Layer1 DL RB Num (Including 0)',
                                'LTE KPI PCell PDSCH PRB Number(Avg)'],
                               ['5G-NR PCell Layer1 DL BLER [%]', 'LTE KPI PCell PDSCH BLER [%]'],
                              ['5G-NR PCell RF CQI', 'LTE KPI PCell WB CQI CW0', 'LTE KPI PCell WB CQI CW1']]

Spark_DT_NR_UL_Export_list = [[DT_LOG_LON],
                               [DT_LOG_LAT],
                               ['5G KPI Total Info Layer2 PDCP UL Throughput(+Split Bearer) [Mbps]',
                                '5G KPI Total Info Layer2 RLC UL Throughput [Mbps]', 'LTE KPI MAC UL Throughput [Mbps]',
                                '5G KPI Total Info Layer2 MAC UL Throughput [Mbps]', 'LTE KPI RLC UL Throughput [Mbps]'],
                               ['5G-NR PCell RF Serving PCI', 'LTE KPI PCell Serving PCI'],
                               ['5G-NR PCell RF Serving SS-RSRP [dBm]', 'LTE KPI PCell Serving RSRP [dBm]'],
                               ['5G-NR PCell RF Serving SS-SINR [dB]', 'LTE KPI PCell SINR [dB]'],
                               ['5G-NR PCell RF Serving SS-RSRQ [dB]', 'LTE KPI PCell Serving RSRQ [dB]'],
                               ['5G-NR PCell RF PUSCH Power [dBm]', 'LTE KPI PCell PUSCH Power [dBm]', 'LTE KPI PCell Total Tx Power [dBm]'],
                               ['5G-NR PCell Layer1 UL MCS (Avg)', 'LTE KPI PCell UL MCS'],
                               ['5G-NR PCell Layer1 UL RB Num (Avg)',
                                '5G-NR PCell Layer1 UL RB Num (Including 0)',
                                'LTE KPI PCell PUSCH PRB Number(Avg)'],
                               ['5G-NR PCell Layer1 UL BLER [%]', 'LTE KPI PCell PDSCH BLER [%]']]

Spark_DT_LTE_DL_Export_list = [[DT_LOG_LON],
                               [DT_LOG_LAT],
                               ['LTE KPI MAC DL Throughput [Mbps]'],
                               ['LTE KPI PCell Serving PCI'],
                               ['LTE KPI PCell Serving RSRP [dBm]'],
                               ['LTE KPI PCell SINR [dB]'],
                               ['LTE KPI PCell Serving RSRQ [dB]'],
                               ['LTE KPI PCell WB RI'],
                               ['LTE KPI PCell DL MCS0', 'LTE KPI PCell DL MCS1'],
                               ['LTE KPI PCell PDSCH PRB Number(Avg)'],
                               ['LTE KPI PCell PDSCH BLER [%]'],
                               ['LTE KPI PCell WB CQI CW0'],
                               ['LTE KPI PCell WB CQI CW1']]

Spark_DT_ENDC_DL_Export_list_New = [[DT_LOG_LON], [DT_LOG_LAT],
                                ['5G KPI Total Info Layer2 PDCP DL Throughput(+Split Bearer) [Mbps]',
                                '5G KPI Total Info Layer2 RLC DL Throughput [Mbps]',
                                '5G KPI Total Info Layer2 MAC DL Throughput [Mbps]',
                                'LTE KPI MAC DL Throughput [Mbps]'],
                                ['5G-NR PCell RF Serving PCI', 'LTE KPI PCell Serving PCI'],
                                ['5G-NR PCell RF Serving SS-RSRP [dBm]', 'LTE KPI PCell Serving RSRP [dBm]'],
                                ['5G-NR PCell RF Serving SS-SINR [dB]', 'LTE KPI PCell SINR [dB]'],
                                ['5G-NR PCell RF Serving SS-RSRQ [dB]', 'LTE KPI PCell Serving RSRQ [dB]'],
                                ['5G-NR PCell RF RI', 'LTE KPI PCell WB RI'],
                                ['5G-NR PCell Layer1 DL MCS (Avg)', 'LTE KPI PCell DL MCS0', 'LTE KPI PCell DL MCS1'],
                                ['5G-NR PCell Layer1 DL RB Num (Avg)',
                                '5G-NR PCell Layer1 DL RB Num (Including 0)',
                                'LTE KPI PCell PDSCH PRB Number(Avg)'],
                                ['5G-NR PCell Layer1 DL BLER [%]', 'LTE KPI PCell PDSCH BLER [%]'],
                              ['5G-NR PCell RF CQI', 'LTE KPI PCell WB CQI CW0', 'LTE KPI PCell WB CQI CW1']]

Spark_DT_ENDC_DL_Export_list_New2 = [[DT_LOG_LON], [DT_LOG_LAT],
                                ['5G-NR Total Info Layer2 PDCP DL Throughput(+Split Bearer) [Mbps]',
                                '5G-NR Total Info Layer2 RLC DL Throughput [Mbps]',
                                '5G-NR Total Info Layer2 MAC DL Throughput [Mbps]',
                                'LTE KPI MAC DL Throughput [Mbps]'],
                                ['5G-NR PCell RF Serving PCI', 'LTE KPI PCell Serving PCI'],
                                ['5G-NR PCell RF Serving SS-RSRP [dBm]', 'LTE KPI PCell Serving RSRP [dBm]'],
                                ['5G-NR PCell RF Serving SS-SINR [dB]', 'LTE KPI PCell SINR [dB]'],
                                ['5G-NR PCell RF Serving SS-RSRQ [dB]', 'LTE KPI PCell Serving RSRQ [dB]'],
                                ['5G-NR PCell RF RI', 'LTE KPI PCell WB RI'],
                                ['5G-NR PCell Layer1 DL MCS (Avg)', 'LTE KPI PCell DL MCS0', 'LTE KPI PCell DL MCS1'],
                                ['5G-NR PCell Layer1 DL RB Num (Avg)',
                                '5G-NR PCell Layer1 DL RB Num (Including 0)',
                                'LTE KPI PCell PDSCH PRB Number(Avg)'],
                                ['5G-NR PCell Layer1 DL BLER [%]', 'LTE KPI PCell PDSCH BLER [%]'],
                              ['5G-NR PCell RF CQI', 'LTE KPI PCell WB CQI CW0', 'LTE KPI PCell WB CQI CW1']]

Spark_DT_Beamforming_DL_Export_list = [[DT_LOG_LON], [DT_LOG_LAT],
                                ['5G-NR Total Info Layer2 PDCP DL Throughput(+Split Bearer) [Mbps]',
                                '5G-NR Total Info Layer2 RLC DL Throughput [Mbps]',
                                '5G-NR Total Info Layer2 MAC DL Throughput [Mbps]',
                                'LTE KPI MAC DL Throughput [Mbps]'],
                                ['5G-NR PCell RF Serving PCI', 'LTE KPI PCell Serving PCI'],
                                ['5G-NR PCell RF Serving SS-RSRP [dBm]', '5G-NR PCell RF Best Beam SS-RSRP [dBm]', 'LTE KPI PCell Serving RSRP [dBm]'],
                                ['5G-NR PCell RF Serving SS-SINR [dB]', '5G-NR PCell RF Best Beam SS-SINR [dBm]', 'LTE KPI PCell SINR [dB]'],
                                ['5G-NR PCell RF Serving SS-RSRQ [dB]', 'LTE KPI PCell Serving RSRQ [dB]'],
                                ['5G-NR PCell RF RI', 'LTE KPI PCell WB RI'],
                                ['5G-NR PCell Layer1 DL MCS (Avg)', 'LTE KPI PCell DL MCS0', 'LTE KPI PCell DL MCS1'],
                                ['5G-NR PCell Layer1 DL RB Num (Avg)',
                                '5G-NR PCell Layer1 DL RB Num (Including 0)',
                                'LTE KPI PCell PDSCH PRB Number(Avg)'],
                                ['5G-NR PCell Layer1 DL BLER [%]', 'LTE KPI PCell PDSCH BLER [%]'],
                              ['5G-NR PCell RF CQI', 'LTE KPI PCell WB CQI CW0', 'LTE KPI PCell WB CQI CW1']]

Spark_DT_Beamforming_DL_Export_list_2 = [[DT_LOG_LON], [DT_LOG_LAT],
                                ['5G KPI Total Info Layer2 PDCP DL Throughput(+Split Bearer) [Mbps]',
                                '5G KPI Total Info Layer2 RLC DL Throughput [Mbps]',
                                '5G KPI Total Info Layer2 MAC DL Throughput [Mbps]',
                                'LTE KPI MAC DL Throughput [Mbps]'],
                                ['5G-NR PCell RF Serving PCI', 'LTE KPI PCell Serving PCI'],
                                ['5G-NR PCell RF Serving SS-RSRP [dBm]', '5G-NR PCell RF Best Beam SS-RSRP [dBm]', 'LTE KPI PCell Serving RSRP [dBm]'],
                                ['5G-NR PCell RF Serving SS-SINR [dB]', '5G-NR PCell RF Best Beam SS-SINR [dBm]', 'LTE KPI PCell SINR [dB]'],
                                ['5G-NR PCell RF Serving SS-RSRQ [dB]', 'LTE KPI PCell Serving RSRQ [dB]'],
                                ['5G-NR PCell RF RI', 'LTE KPI PCell WB RI'],
                                ['5G-NR PCell Layer1 DL MCS (Avg)', 'LTE KPI PCell DL MCS0', 'LTE KPI PCell DL MCS1'],
                                ['5G-NR PCell Layer1 DL RB Num (Avg)',
                                '5G-NR PCell Layer1 DL RB Num (Including 0)',
                                'LTE KPI PCell PDSCH PRB Number(Avg)'],
                                ['5G-NR PCell Layer1 DL BLER [%]', 'LTE KPI PCell PDSCH BLER [%]'],
                              ['5G-NR PCell RF CQI', 'LTE KPI PCell WB CQI CW0', 'LTE KPI PCell WB CQI CW1']]

Spark_DT_Beamforming_DL_Export_list_2_no_BF = [[DT_LOG_LON], [DT_LOG_LAT],
                                ['5G KPI Total Info Layer2 PDCP DL Throughput(+Split Bearer) [Mbps]',
                                '5G KPI Total Info Layer2 RLC DL Throughput [Mbps]',
                                '5G KPI Total Info Layer2 MAC DL Throughput [Mbps]',
                                'LTE KPI MAC DL Throughput [Mbps]'],
                                ['5G-NR PCell RF Serving PCI', 'LTE KPI PCell Serving PCI'],
                                ['5G-NR PCell RF Serving SS-RSRP [dBm]', 'LTE KPI PCell Serving RSRP [dBm]'],
                                ['5G-NR PCell RF Serving SS-SINR [dB]', 'LTE KPI PCell SINR [dB]'],
                                ['5G-NR PCell RF Serving SS-RSRQ [dB]', 'LTE KPI PCell Serving RSRQ [dB]'],
                                ['5G-NR PCell RF RI', 'LTE KPI PCell WB RI'],
                                ['5G-NR PCell Layer1 DL MCS (Avg)', 'LTE KPI PCell DL MCS0', 'LTE KPI PCell DL MCS1'],
                                ['5G-NR PCell Layer1 DL RB Num (Avg)',
                                '5G-NR PCell Layer1 DL RB Num (Including 0)',
                                'LTE KPI PCell PDSCH PRB Number(Avg)'],
                                ['5G-NR PCell Layer1 DL BLER [%]', 'LTE KPI PCell PDSCH BLER [%]'],
                              ['5G-NR PCell RF CQI', 'LTE KPI PCell WB CQI CW0', 'LTE KPI PCell WB CQI CW1']]

Spark_DT_Beamforming_UL_Export_list = [[DT_LOG_LON], [DT_LOG_LAT],
                                ['5G-NR Total Info Layer2 PDCP UL Throughput(+Split Bearer) [Mbps]',
                                '5G-NR Total Info Layer2 RLC UL Throughput [Mbps]',
                                '5G-NR Total Info Layer2 MAC UL Throughput [Mbps]',
                                'LTE KPI MAC UL Throughput [Mbps]'],
                                ['5G-NR PCell RF Serving PCI', 'LTE KPI PCell Serving PCI'],
                                ['5G-NR PCell RF Serving SS-RSRP [dBm]', '5G-NR PCell RF Best Beam SS-RSRP [dBm]', 'LTE KPI PCell Serving RSRP [dBm]'],
                                ['5G-NR PCell RF Serving SS-SINR [dB]', '5G-NR PCell RF Best Beam SS-SINR [dBm]', 'LTE KPI PCell SINR [dB]'],
                                ['5G-NR PCell RF Serving SS-RSRQ [dB]', 'LTE KPI PCell Serving RSRQ [dB]', 'LTE KPI PCell Serving RSRQ [dB]'],
                                ['5G-NR PCell RF PUSCH Power [dBm]', 'LTE KPI PCell PUSCH Power [dBm]',
                                 'LTE KPI PCell Total Tx Power [dBm]'],
                                ['5G-NR PCell Layer1 UL MCS (Avg)', 'LTE KPI PCell UL MCS'],
                                ['5G-NR PCell Layer1 UL RB Num (Avg)',
                                '5G-NR PCell Layer1 UL RB Num (Including 0)',
                                'LTE KPI PCell PUSCH PRB Number(Avg)'],
                                ['5G-NR PCell Layer1 UL BLER [%]', 'LTE KPI PCell PUSCH BLER [%]'],
                                ['5G-NR PCell RF Pathloss [dB]'],
                                ['PCell Summary Serving Distance']]

Spark_DT_Beamforming_UL_Export_list_2 = [[DT_LOG_LON], [DT_LOG_LAT],
                                ['5G KPI Total Info Layer2 PDCP UL Throughput(+Split Bearer) [Mbps]',
                                '5G KPI Total Info Layer2 RLC UL Throughput [Mbps]',
                                '5G KPI Total Info Layer2 MAC UL Throughput [Mbps]',
                                'LTE KPI MAC UL Throughput [Mbps]'],
                                ['5G-NR PCell RF Serving PCI', 'LTE KPI PCell Serving PCI'],
                                ['5G-NR PCell RF Serving SS-RSRP [dBm]', '5G-NR PCell RF Best Beam SS-RSRP [dBm]', 'LTE KPI PCell Serving RSRP [dBm]'],
                                ['5G-NR PCell RF Serving SS-SINR [dB]', '5G-NR PCell RF Best Beam SS-SINR [dBm]', 'LTE KPI PCell SINR [dB]'],
                                ['5G-NR PCell RF Serving SS-RSRQ [dB]', 'LTE KPI PCell Serving RSRQ [dB]', 'LTE KPI PCell Serving RSRQ [dB]'],
                                ['5G-NR PCell RF PUSCH Power [dBm]', 'LTE KPI PCell PUSCH Power [dBm]',
                                 'LTE KPI PCell Total Tx Power [dBm]'],
                                ['5G-NR PCell Layer1 UL MCS (Avg)', 'LTE KPI PCell UL MCS'],
                                ['5G-NR PCell Layer1 UL RB Num (Avg)',
                                '5G-NR PCell Layer1 UL RB Num (Including 0)',
                                'LTE KPI PCell PUSCH PRB Number(Avg)'],
                                ['5G-NR PCell Layer1 UL BLER [%]', 'LTE KPI PCell PUSCH BLER [%]'],
                                ['5G-NR PCell RF Pathloss [dB]'],
                                ['PCell Summary Serving Distance']]

Spark_DT_ENDC_UL_Export_list_New = [[DT_LOG_LON], [DT_LOG_LAT],
                                ['5G-NR Total Info Layer2 PDCP UL Throughput(+Split Bearer) [Mbps]',
                                '5G-NR Total Info Layer2 RLC UL Throughput [Mbps]',
                                '5G-NR Total Info Layer2 MAC UL Throughput [Mbps]',
                                'LTE KPI MAC UL Throughput [Mbps]'],
                                ['5G-NR PCell RF Serving PCI', 'LTE KPI PCell Serving PCI'],
                                ['5G-NR PCell RF Serving SS-RSRP [dBm]', 'LTE KPI PCell Serving RSRP [dBm]'],
                                ['5G-NR PCell RF Serving SS-SINR [dB]', 'LTE KPI PCell SINR [dB]'],
                                ['5G-NR PCell RF Serving SS-RSRQ [dB]', 'LTE KPI PCell Serving RSRQ [dB]'],
                                ['5G-NR PCell RF PUSCH Power [dBm]', 'LTE KPI PCell PUSCH Power [dBm]',
                                 'LTE KPI PCell Total Tx Power [dBm]'],
                                ['5G-NR PCell Layer1 UL MCS (Avg)', 'LTE KPI PCell UL MCS'],
                                ['5G-NR PCell Layer1 UL RB Num (Avg)',
                                '5G-NR PCell Layer1 UL RB Num (Including 0)',
                                'LTE KPI PCell PUSCH PRB Number(Avg)'],
                                ['5G-NR PCell Layer1 UL BLER [%]', 'LTE KPI PCell PUSCH BLER [%]']]

# ========================== New DT Template ============================
Spark_DT_ENDC_Thick_DL = [[DT_LOG_LON], [DT_LOG_LAT],
                          ['Total Info Layer2 PDCP DL Throughput(+Split Bearer) [Mbps]',
                           'Total Info Layer2 RLC DL Throughput [Mbps]',
                           'Total Info Layer2 RLC DL Throughput per PRB [Mbps]',
                           'Total Info Layer2 MAC DL Throughput [Mbps]',
                           'LTE KPI RLC DL Throughput [Mbps]',
                           'LTE KPI MAC DL Throughput [Mbps]',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 MAC DL Throughput',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 MAC DL Throughput',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 MAC DL Throughput',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 MAC DL Throughput',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39250 MAC DL Throughput',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39052 MAC DL Throughput',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 38854 MAC DL Throughput'],
                          ['5G-NR PCell RF Serving PCI', 'LTE KPI PCell Serving PCI'],
                          ['5G-NR PCell RF Serving SS-RSRP [dBm]', '5G-NR PCell RF Best Beam SS-RSRP [dBm]',
                           'LTE KPI PCell Serving RSRP [dBm]',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 Serving RSRP',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 Serving RSRP',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 Serving RSRP',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 Serving RSRP',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39250 Serving RSRP',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39052 Serving RSRP',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 38854 Serving RSRP'],
                          ['5G-NR PCell RF Serving SS-SINR [dB]', '5G-NR PCell RF Best Beam SS-SINR [dB]',
                           'LTE KPI PCell SINR [dB]',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 SINR',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 SINR',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 SINR',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 SINR',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39250 SINR',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39052 SINR',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 38854 SINR'],
                          ['5G-NR PCell RF Serving SS-RSRQ [dB]', 'LTE KPI PCell Serving RSRQ [dB]'],
                          ['5G-NR PCell RF RI', 'LTE KPI PCell WB RI',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 WB RI',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 WB RI',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 WB RI',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 WB RI',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39250 WB RI',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39052 WB RI',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 38854 WB RI'],
                          ['5G-NR PCell Layer1 DL MCS (Avg)', 'LTE KPI PCell DL MCS0', 'LTE KPI PCell DL MCS1',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 DL MCS0',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 DL MCS0',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 DL MCS0',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 DL MCS0',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39250 DL MCS0',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39052 DL MCS0',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 38854 DL MCS0',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 DL MCS1',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 DL MCS1',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 DL MCS1',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 DL MCS1',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39250 DL MCS1',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39052 DL MCS1',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 38854 DL MCS1'],
                          ['5G-NR PCell Layer1 DL RB Num (Avg)',
                           '5G-NR PCell Layer1 DL RB Num (Including 0)',
                           'LTE KPI PCell PDSCH PRB Number(Avg)',
                           'LTE KPI PCell PDSCH PRB Number(Including 0)',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 PDSCH PRB Number',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 PDSCH PRB Number',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 PDSCH PRB Number',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 PDSCH PRB Number',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39250 PDSCH PRB Number',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39052 PDSCH PRB Number',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 38854 PDSCH PRB Number'],
                          ['5G-NR PCell Layer1 DL BLER [%]', 'LTE KPI PCell PDSCH BLER [%]',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 PDSCH BLER',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 PDSCH BLER',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 PDSCH BLER',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 PDSCH BLER',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39250 PDSCH BLER',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39052 PDSCH BLER',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 38854 PDSCH BLER'],
                          ['5G-NR PCell RF CQI', 'LTE KPI PCell WB CQI CW0', 'LTE KPI PCell WB CQI CW1',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 WB CQI CW0',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 WB CQI CW0',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 WB CQI CW0',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 WB CQI CW0',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39250 WB CQI CW0',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39052 WB CQI CW0',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 38854 WB CQI CW0',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 WB CQI CW1',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 WB CQI CW1',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 WB CQI CW1',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 WB CQI CW1',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39250 WB CQI CW1',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39052 WB CQI CW1',
                           'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 38854 WB CQI CW1'],
                          ['5G-NR PCell RF Pathloss [dB]'],
                          ['5G-NR PCell RF PUSCH Power [dBm]']]

Spark_DT_ENDC_Thick_UL = [[DT_LOG_LON], [DT_LOG_LAT],
                                ['Total Info Layer2 PDCP UL Throughput(+Split Bearer) [Mbps]',
                                 'Total Info Layer2 RLC UL Throughput [Mbps]',
                                 'Total Info Layer2 RLC UL Throughput per PRB [Mbps]',
                                 'Total Info Layer2 MAC UL Throughput [Mbps]',
                                 'LTE KPI RLC UL Throughput [Mbps]',
                                 'LTE KPI MAC UL Throughput [Mbps]',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 MAC UL Throughput',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 MAC UL Throughput',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 MAC UL Throughput',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 MAC UL Throughput',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39250 MAC UL Throughput',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39052 MAC UL Throughput',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 38854 MAC UL Throughput'],
                                ['5G-NR PCell RF Serving PCI', 'LTE KPI PCell Serving PCI',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 Serving PCI',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 Serving PCI',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 Serving PCI',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 Serving PCI',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39250 Serving PCI',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39052 Serving PCI',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 38854 Serving PCI'],
                                ['5G-NR PCell RF Serving SS-RSRP [dBm]', '5G-NR PCell RF Best Beam SS-RSRP [dBm]',
                                 'LTE KPI PCell Serving RSRP [dBm]',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 Serving RSRP',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 Serving RSRP',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 Serving RSRP',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 Serving RSRP',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39250 Serving RSRP',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39052 Serving RSRP',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 38854 Serving RSRP'],
                                ['5G-NR PCell RF Serving SS-SINR [dB]', '5G-NR PCell RF Best Beam SS-SINR [dB]',
                                 'LTE KPI PCell SINR [dB]',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 SINR',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 SINR',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 SINR',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 SINR',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39250 SINR',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39052 SINR',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 38854 SINR'],
                                ['5G-NR PCell RF Serving SS-RSRQ [dB]', 'LTE KPI PCell Serving RSRQ [dB]'],
                                ['5G-NR PCell RF PUSCH Power [dBm]', 'LTE KPI PCell PUSCH Power [dBm]',
                                 'LTE KPI PCell Total Tx Power [dBm]'],
                                ['5G-NR PCell Layer1 UL MCS (Avg)', 'LTE KPI PCell UL MCS',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 UL MCS',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 UL MCS',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 UL MCS',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 UL MCS',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39250 UL MCS',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39052 UL MCS',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 38854 UL MCS'],
                                ['5G-NR PCell Layer1 UL RB Num (Avg)',
                                 '5G-NR PCell Layer1 UL RB Num (Including 0)',
                                 'LTE KPI PCell PUSCH PRB Number(Avg)',
                                 'LTE KPI PCell PUSCH PRB Number(Including 0)',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 PUSCH PRB Number',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 PUSCH PRB Number',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 PUSCH PRB Number',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 PUSCH PRB Number',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39250 PUSCH PRB Number',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39052 PUSCH PRB Number',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 38854 PUSCH PRB Number'],
                                ['5G-NR PCell Layer1 UL BLER [%]', 'LTE KPI PCell PUSCH BLER [%]',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 9310 PUSCH BLER',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 1600 PUSCH BLER',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 275 PUSCH BLER',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 3200 PUSCH BLER',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39250 PUSCH BLER',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 39052 PUSCH BLER',
                                 'LTE KPI per EARFCN(Based on PCell+SCell) DL EARFCN 38854 PUSCH BLER'],
                                ['5G-NR PCell RF Pathloss [dB]']]

Spark_DT_ENDC_Thick_Scanner = [[DT_LOG_LON], [DT_LOG_LAT],
                                ['Top Set Top 1 PCI'],
                                ['Top Set Top 1 SSB_Idx'],
                                ['Top Set Top 1 SSS_RP [dBm]', 'Top Set Top 1 PSS_RP [dBm]',
                                 'Top Set Top 1 RS_PBCH_RP [dBm]', 'Top Set Top 1 SSB_RP [dBm]'],
                                ['Top Set Top 1 SSS_CINR [dB]', 'Top Set Top 1 PSS_CINR [dB]',
                                 'Top Set Top 1 RS_PBCH_CINR [dB]', 'Top Set Top 1 SSB_CINR [dB]',
                                 'Top Set Top 1 SS_CINR [dB]'],
                                ['Top Set Top 1 SSS_RQ [dB]', 'Top Set Top 1 PSS_RQ [dB]',
                                 'Top Set Top 1 RS_PBCH_RQ [dB]', 'Top Set Top 1 SSB_RQ [dB]'],
                                ['Top Set Top 1 SSS_delaySpread'],
                                ['Top Set Top 1 Time Offset'],
                                ['Top Set Top 1 Half Frame Number']]